//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace blogNetCore.Internacionalizacao {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class traducao {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal traducao() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("blogNetCore.Internacionalizacao.traducao", typeof(traducao).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ir_para_o_site {
            get {
                return ResourceManager.GetString("ir_para_o_site", resourceCulture);
            }
        }
        
        public static string categoria {
            get {
                return ResourceManager.GetString("categoria", resourceCulture);
            }
        }
        
        public static string post {
            get {
                return ResourceManager.GetString("post", resourceCulture);
            }
        }
        
        public static string contato {
            get {
                return ResourceManager.GetString("contato", resourceCulture);
            }
        }
        
        public static string idiomas {
            get {
                return ResourceManager.GetString("idiomas", resourceCulture);
            }
        }
        
        public static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        public static string nova_categoria {
            get {
                return ResourceManager.GetString("nova_categoria", resourceCulture);
            }
        }
        
        public static string descricao {
            get {
                return ResourceManager.GetString("descricao", resourceCulture);
            }
        }
        
        public static string editar {
            get {
                return ResourceManager.GetString("editar", resourceCulture);
            }
        }
        
        public static string excluir {
            get {
                return ResourceManager.GetString("excluir", resourceCulture);
            }
        }
        
        public static string voltar {
            get {
                return ResourceManager.GetString("voltar", resourceCulture);
            }
        }
        
        public static string enviar {
            get {
                return ResourceManager.GetString("enviar", resourceCulture);
            }
        }
        
        public static string novo_post {
            get {
                return ResourceManager.GetString("novo_post", resourceCulture);
            }
        }
        
        public static string titulo {
            get {
                return ResourceManager.GetString("titulo", resourceCulture);
            }
        }
        
        public static string conteudo {
            get {
                return ResourceManager.GetString("conteudo", resourceCulture);
            }
        }
        
        public static string resumo {
            get {
                return ResourceManager.GetString("resumo", resourceCulture);
            }
        }
        
        public static string tag {
            get {
                return ResourceManager.GetString("tag", resourceCulture);
            }
        }
        
        public static string nome {
            get {
                return ResourceManager.GetString("nome", resourceCulture);
            }
        }
        
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        public static string telefone {
            get {
                return ResourceManager.GetString("telefone", resourceCulture);
            }
        }
        
        public static string mensagem {
            get {
                return ResourceManager.GetString("mensagem", resourceCulture);
            }
        }
        
        public static string campo_obrigatorio {
            get {
                return ResourceManager.GetString("campo_obrigatorio", resourceCulture);
            }
        }
    }
}
